-- Auto-generated seed data for object_catalog (Section 3.3).
-- 20 categories x 50 objects each = 1000 rows.

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (1, 'Kitchen', 'Frying Pan', '🍳'),
  (2, 'Kitchen', 'Spatula', '🍳'),
  (3, 'Kitchen', 'Whisk', '🍳'),
  (4, 'Kitchen', 'Mixing Bowl', '🍳'),
  (5, 'Kitchen', 'Cutting Board', '🍳'),
  (6, 'Kitchen', 'Chef Knife', '🍳'),
  (7, 'Kitchen', 'Toaster', '🍳'),
  (8, 'Kitchen', 'Blender', '🍳'),
  (9, 'Kitchen', 'Kettle', '🍳'),
  (10, 'Kitchen', 'Saucepan', '🍳'),
  (11, 'Kitchen', 'Ladle', '🍳'),
  (12, 'Kitchen', 'Rolling Pin', '🍳'),
  (13, 'Kitchen', 'Colander', '🍳'),
  (14, 'Kitchen', 'Grater', '🍳'),
  (15, 'Kitchen', 'Oven Mitt', '🍳'),
  (16, 'Kitchen', 'Apron', '🍳'),
  (17, 'Kitchen', 'Coffee Mug', '🍳'),
  (18, 'Kitchen', 'Teapot', '🍳'),
  (19, 'Kitchen', 'Peeler', '🍳'),
  (20, 'Kitchen', 'Can Opener', '🍳'),
  (21, 'Kitchen', 'Measuring Cup', '🍳'),
  (22, 'Kitchen', 'Baking Tray', '🍳'),
  (23, 'Kitchen', 'Muffin Tin', '🍳'),
  (24, 'Kitchen', 'Wooden Spoon', '🍳'),
  (25, 'Kitchen', 'Tongs', '🍳'),
  (26, 'Kitchen', 'Bread Knife', '🍳'),
  (27, 'Kitchen', 'Cheese Board', '🍳'),
  (28, 'Kitchen', 'Salt Shaker', '🍳'),
  (29, 'Kitchen', 'Pepper Mill', '🍳'),
  (30, 'Kitchen', 'Dish Towel', '🍳'),
  (31, 'Kitchen', 'Skillet', '🍳'),
  (32, 'Kitchen', 'Pot Lid', '🍳'),
  (33, 'Kitchen', 'Egg Timer', '🍳'),
  (34, 'Kitchen', 'Garlic Press', '🍳'),
  (35, 'Kitchen', 'Ice Tray', '🍳'),
  (36, 'Kitchen', 'Cookie Cutter', '🍳'),
  (37, 'Kitchen', 'Fruit Bowl', '🍳'),
  (38, 'Kitchen', 'Bottle Opener', '🍳'),
  (39, 'Kitchen', 'Strainer', '🍳'),
  (40, 'Kitchen', 'Trivet', '🍳'),
  (41, 'Kitchen', 'Tiny Frying Pan', '🍳'),
  (42, 'Kitchen', 'Tiny Spatula', '🍳'),
  (43, 'Kitchen', 'Tiny Whisk', '🍳'),
  (44, 'Kitchen', 'Tiny Mixing Bowl', '🍳'),
  (45, 'Kitchen', 'Tiny Cutting Board', '🍳'),
  (46, 'Kitchen', 'Tiny Chef Knife', '🍳'),
  (47, 'Kitchen', 'Tiny Toaster', '🍳'),
  (48, 'Kitchen', 'Tiny Blender', '🍳'),
  (49, 'Kitchen', 'Tiny Kettle', '🍳'),
  (50, 'Kitchen', 'Tiny Saucepan', '🍳');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (51, 'Bedroom', 'Pillow', '🛏️'),
  (52, 'Bedroom', 'Blanket', '🛏️'),
  (53, 'Bedroom', 'Alarm Clock', '🛏️'),
  (54, 'Bedroom', 'Nightstand', '🛏️'),
  (55, 'Bedroom', 'Lamp', '🛏️'),
  (56, 'Bedroom', 'Wardrobe', '🛏️'),
  (57, 'Bedroom', 'Mirror', '🛏️'),
  (58, 'Bedroom', 'Hanger', '🛏️'),
  (59, 'Bedroom', 'Slippers', '🛏️'),
  (60, 'Bedroom', 'Bathrobe', '🛏️'),
  (61, 'Bedroom', 'Curtain', '🛏️'),
  (62, 'Bedroom', 'Photo Frame', '🛏️'),
  (63, 'Bedroom', 'Jewelry Box', '🛏️'),
  (64, 'Bedroom', 'Perfume Bottle', '🛏️'),
  (65, 'Bedroom', 'Hairbrush', '🛏️'),
  (66, 'Bedroom', 'Candle', '🛏️'),
  (67, 'Bedroom', 'Diary', '🛏️'),
  (68, 'Bedroom', 'Rug', '🛏️'),
  (69, 'Bedroom', 'Bed Frame', '🛏️'),
  (70, 'Bedroom', 'Mattress', '🛏️'),
  (71, 'Bedroom', 'Reading Lamp', '🛏️'),
  (72, 'Bedroom', 'Coat Rack', '🛏️'),
  (73, 'Bedroom', 'Quilt', '🛏️'),
  (74, 'Bedroom', 'Sleep Mask', '🛏️'),
  (75, 'Bedroom', 'Music Box', '🛏️'),
  (76, 'Bedroom', 'Bookshelf', '🛏️'),
  (77, 'Bedroom', 'Laundry Basket', '🛏️'),
  (78, 'Bedroom', 'Wall Clock', '🛏️'),
  (79, 'Bedroom', 'Vanity Mirror', '🛏️'),
  (80, 'Bedroom', 'Throw Pillow', '🛏️'),
  (81, 'Bedroom', 'Tiny Pillow', '🛏️'),
  (82, 'Bedroom', 'Tiny Blanket', '🛏️'),
  (83, 'Bedroom', 'Tiny Alarm Clock', '🛏️'),
  (84, 'Bedroom', 'Tiny Nightstand', '🛏️'),
  (85, 'Bedroom', 'Tiny Lamp', '🛏️'),
  (86, 'Bedroom', 'Tiny Wardrobe', '🛏️'),
  (87, 'Bedroom', 'Tiny Mirror', '🛏️'),
  (88, 'Bedroom', 'Tiny Hanger', '🛏️'),
  (89, 'Bedroom', 'Tiny Slippers', '🛏️'),
  (90, 'Bedroom', 'Tiny Bathrobe', '🛏️'),
  (91, 'Bedroom', 'Tiny Curtain', '🛏️'),
  (92, 'Bedroom', 'Tiny Photo Frame', '🛏️'),
  (93, 'Bedroom', 'Tiny Jewelry Box', '🛏️'),
  (94, 'Bedroom', 'Tiny Perfume Bottle', '🛏️'),
  (95, 'Bedroom', 'Tiny Hairbrush', '🛏️'),
  (96, 'Bedroom', 'Tiny Candle', '🛏️'),
  (97, 'Bedroom', 'Tiny Diary', '🛏️'),
  (98, 'Bedroom', 'Tiny Rug', '🛏️'),
  (99, 'Bedroom', 'Tiny Bed Frame', '🛏️'),
  (100, 'Bedroom', 'Tiny Mattress', '🛏️');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (101, 'Office', 'Stapler', '📎'),
  (102, 'Office', 'Paperclip', '📎'),
  (103, 'Office', 'Notebook', '📎'),
  (104, 'Office', 'Pen', '📎'),
  (105, 'Office', 'Pencil', '📎'),
  (106, 'Office', 'Calculator', '📎'),
  (107, 'Office', 'Desk Lamp', '📎'),
  (108, 'Office', 'Filing Cabinet', '📎'),
  (109, 'Office', 'Sticky Notes', '📎'),
  (110, 'Office', 'Envelope', '📎'),
  (111, 'Office', 'Hole Punch', '📎'),
  (112, 'Office', 'Scissors', '📎'),
  (113, 'Office', 'Tape Dispenser', '📎'),
  (114, 'Office', 'Rubber Stamp', '📎'),
  (115, 'Office', 'Calendar', '📎'),
  (116, 'Office', 'Keyboard', '📎'),
  (117, 'Office', 'Mouse', '📎'),
  (118, 'Office', 'Monitor', '📎'),
  (119, 'Office', 'Printer', '📎'),
  (120, 'Office', 'Whiteboard', '📎'),
  (121, 'Office', 'Marker', '📎'),
  (122, 'Office', 'Binder', '📎'),
  (123, 'Office', 'Clipboard', '📎'),
  (124, 'Office', 'Ruler', '📎'),
  (125, 'Office', 'Pushpin', '📎'),
  (126, 'Office', 'Eraser', '📎'),
  (127, 'Office', 'Highlighter', '📎'),
  (128, 'Office', 'Business Card', '📎'),
  (129, 'Office', 'Desk Organizer', '📎'),
  (130, 'Office', 'Chair', '📎'),
  (131, 'Office', 'Tiny Stapler', '📎'),
  (132, 'Office', 'Tiny Paperclip', '📎'),
  (133, 'Office', 'Tiny Notebook', '📎'),
  (134, 'Office', 'Tiny Pen', '📎'),
  (135, 'Office', 'Tiny Pencil', '📎'),
  (136, 'Office', 'Tiny Calculator', '📎'),
  (137, 'Office', 'Tiny Desk Lamp', '📎'),
  (138, 'Office', 'Tiny Filing Cabinet', '📎'),
  (139, 'Office', 'Tiny Sticky Notes', '📎'),
  (140, 'Office', 'Tiny Envelope', '📎'),
  (141, 'Office', 'Tiny Hole Punch', '📎'),
  (142, 'Office', 'Tiny Scissors', '📎'),
  (143, 'Office', 'Tiny Tape Dispenser', '📎'),
  (144, 'Office', 'Tiny Rubber Stamp', '📎'),
  (145, 'Office', 'Tiny Calendar', '📎'),
  (146, 'Office', 'Tiny Keyboard', '📎'),
  (147, 'Office', 'Tiny Mouse', '📎'),
  (148, 'Office', 'Tiny Monitor', '📎'),
  (149, 'Office', 'Tiny Printer', '📎'),
  (150, 'Office', 'Tiny Whiteboard', '📎');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (151, 'School', 'Backpack', '🎒'),
  (152, 'School', 'Textbook', '🎒'),
  (153, 'School', 'Chalk', '🎒'),
  (154, 'School', 'Blackboard', '🎒'),
  (155, 'School', 'Globe', '🎒'),
  (156, 'School', 'Ruler', '🎒'),
  (157, 'School', 'Protractor', '🎒'),
  (158, 'School', 'Compass', '🎒'),
  (159, 'School', 'Glue Stick', '🎒'),
  (160, 'School', 'Crayon', '🎒'),
  (161, 'School', 'Notebook', '🎒'),
  (162, 'School', 'Lunchbox', '🎒'),
  (163, 'School', 'Pencil Case', '🎒'),
  (164, 'School', 'Eraser', '🎒'),
  (165, 'School', 'Report Card', '🎒'),
  (166, 'School', 'School Bus', '🎒'),
  (167, 'School', 'Locker', '🎒'),
  (168, 'School', 'Whistle', '🎒'),
  (169, 'School', 'Trophy', '🎒'),
  (170, 'School', 'Diploma', '🎒'),
  (171, 'School', 'Microscope', '🎒'),
  (172, 'School', 'Test Tube', '🎒'),
  (173, 'School', 'Map', '🎒'),
  (174, 'School', 'Flashcard', '🎒'),
  (175, 'School', 'Calculator', '🎒'),
  (176, 'School', 'Chalkboard Eraser', '🎒'),
  (177, 'School', 'Bell', '🎒'),
  (178, 'School', 'Gym Shoe', '🎒'),
  (179, 'School', 'Water Bottle', '🎒'),
  (180, 'School', 'Name Tag', '🎒'),
  (181, 'School', 'Tiny Backpack', '🎒'),
  (182, 'School', 'Tiny Textbook', '🎒'),
  (183, 'School', 'Tiny Chalk', '🎒'),
  (184, 'School', 'Tiny Blackboard', '🎒'),
  (185, 'School', 'Tiny Globe', '🎒'),
  (186, 'School', 'Tiny Ruler', '🎒'),
  (187, 'School', 'Tiny Protractor', '🎒'),
  (188, 'School', 'Tiny Compass', '🎒'),
  (189, 'School', 'Tiny Glue Stick', '🎒'),
  (190, 'School', 'Tiny Crayon', '🎒'),
  (191, 'School', 'Tiny Notebook', '🎒'),
  (192, 'School', 'Tiny Lunchbox', '🎒'),
  (193, 'School', 'Tiny Pencil Case', '🎒'),
  (194, 'School', 'Tiny Eraser', '🎒'),
  (195, 'School', 'Tiny Report Card', '🎒'),
  (196, 'School', 'Tiny School Bus', '🎒'),
  (197, 'School', 'Tiny Locker', '🎒'),
  (198, 'School', 'Tiny Whistle', '🎒'),
  (199, 'School', 'Tiny Trophy', '🎒'),
  (200, 'School', 'Tiny Diploma', '🎒');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (201, 'Garden', 'Shovel', '🌱'),
  (202, 'Garden', 'Rake', '🌱'),
  (203, 'Garden', 'Watering Can', '🌱'),
  (204, 'Garden', 'Flower Pot', '🌱'),
  (205, 'Garden', 'Garden Hose', '🌱'),
  (206, 'Garden', 'Wheelbarrow', '🌱'),
  (207, 'Garden', 'Trowel', '🌱'),
  (208, 'Garden', 'Pruning Shears', '🌱'),
  (209, 'Garden', 'Seed Packet', '🌱'),
  (210, 'Garden', 'Sun Hat', '🌱'),
  (211, 'Garden', 'Gardening Gloves', '🌱'),
  (212, 'Garden', 'Birdhouse', '🌱'),
  (213, 'Garden', 'Scarecrow', '🌱'),
  (214, 'Garden', 'Sprinkler', '🌱'),
  (215, 'Garden', 'Compost Bin', '🌱'),
  (216, 'Garden', 'Garden Gnome', '🌱'),
  (217, 'Garden', 'Trellis', '🌱'),
  (218, 'Garden', 'Wind Chime', '🌱'),
  (219, 'Garden', 'Rake Head', '🌱'),
  (220, 'Garden', 'Fence Post', '🌱'),
  (221, 'Garden', 'Flower Basket', '🌱'),
  (222, 'Garden', 'Watering Wand', '🌱'),
  (223, 'Garden', 'Plant Stake', '🌱'),
  (224, 'Garden', 'Greenhouse', '🌱'),
  (225, 'Garden', 'Lawn Mower', '🌱'),
  (226, 'Garden', 'Weed Puller', '🌱'),
  (227, 'Garden', 'Garden Bench', '🌱'),
  (228, 'Garden', 'Sundial', '🌱'),
  (229, 'Garden', 'Bug Net', '🌱'),
  (230, 'Garden', 'Potting Soil Bag', '🌱'),
  (231, 'Garden', 'Tiny Shovel', '🌱'),
  (232, 'Garden', 'Tiny Rake', '🌱'),
  (233, 'Garden', 'Tiny Watering Can', '🌱'),
  (234, 'Garden', 'Tiny Flower Pot', '🌱'),
  (235, 'Garden', 'Tiny Garden Hose', '🌱'),
  (236, 'Garden', 'Tiny Wheelbarrow', '🌱'),
  (237, 'Garden', 'Tiny Trowel', '🌱'),
  (238, 'Garden', 'Tiny Pruning Shears', '🌱'),
  (239, 'Garden', 'Tiny Seed Packet', '🌱'),
  (240, 'Garden', 'Tiny Sun Hat', '🌱'),
  (241, 'Garden', 'Tiny Gardening Gloves', '🌱'),
  (242, 'Garden', 'Tiny Birdhouse', '🌱'),
  (243, 'Garden', 'Tiny Scarecrow', '🌱'),
  (244, 'Garden', 'Tiny Sprinkler', '🌱'),
  (245, 'Garden', 'Tiny Compost Bin', '🌱'),
  (246, 'Garden', 'Tiny Garden Gnome', '🌱'),
  (247, 'Garden', 'Tiny Trellis', '🌱'),
  (248, 'Garden', 'Tiny Wind Chime', '🌱'),
  (249, 'Garden', 'Tiny Rake Head', '🌱'),
  (250, 'Garden', 'Tiny Fence Post', '🌱');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (251, 'Electronics', 'Smartphone', '🔌'),
  (252, 'Electronics', 'Laptop', '🔌'),
  (253, 'Electronics', 'Headphones', '🔌'),
  (254, 'Electronics', 'Charger', '🔌'),
  (255, 'Electronics', 'USB Cable', '🔌'),
  (256, 'Electronics', 'Tablet', '🔌'),
  (257, 'Electronics', 'Camera', '🔌'),
  (258, 'Electronics', 'Remote Control', '🔌'),
  (259, 'Electronics', 'Speaker', '🔌'),
  (260, 'Electronics', 'Router', '🔌'),
  (261, 'Electronics', 'Power Bank', '🔌'),
  (262, 'Electronics', 'Game Controller', '🔌'),
  (263, 'Electronics', 'Smartwatch', '🔌'),
  (264, 'Electronics', 'Earbuds', '🔌'),
  (265, 'Electronics', 'Webcam', '🔌'),
  (266, 'Electronics', 'Flash Drive', '🔌'),
  (267, 'Electronics', 'Extension Cord', '🔌'),
  (268, 'Electronics', 'Battery Pack', '🔌'),
  (269, 'Electronics', 'Microphone', '🔌'),
  (270, 'Electronics', 'Projector', '🔌'),
  (271, 'Electronics', 'Drone', '🔌'),
  (272, 'Electronics', 'Keyboard', '🔌'),
  (273, 'Electronics', 'Mouse', '🔌'),
  (274, 'Electronics', 'Monitor', '🔌'),
  (275, 'Electronics', 'Circuit Board', '🔌'),
  (276, 'Electronics', 'Light Bulb', '🔌'),
  (277, 'Electronics', 'Fan', '🔌'),
  (278, 'Electronics', 'Calculator', '🔌'),
  (279, 'Electronics', 'Radio', '🔌'),
  (280, 'Electronics', 'VR Headset', '🔌'),
  (281, 'Electronics', 'Tiny Smartphone', '🔌'),
  (282, 'Electronics', 'Tiny Laptop', '🔌'),
  (283, 'Electronics', 'Tiny Headphones', '🔌'),
  (284, 'Electronics', 'Tiny Charger', '🔌'),
  (285, 'Electronics', 'Tiny USB Cable', '🔌'),
  (286, 'Electronics', 'Tiny Tablet', '🔌'),
  (287, 'Electronics', 'Tiny Camera', '🔌'),
  (288, 'Electronics', 'Tiny Remote Control', '🔌'),
  (289, 'Electronics', 'Tiny Speaker', '🔌'),
  (290, 'Electronics', 'Tiny Router', '🔌'),
  (291, 'Electronics', 'Tiny Power Bank', '🔌'),
  (292, 'Electronics', 'Tiny Game Controller', '🔌'),
  (293, 'Electronics', 'Tiny Smartwatch', '🔌'),
  (294, 'Electronics', 'Tiny Earbuds', '🔌'),
  (295, 'Electronics', 'Tiny Webcam', '🔌'),
  (296, 'Electronics', 'Tiny Flash Drive', '🔌'),
  (297, 'Electronics', 'Tiny Extension Cord', '🔌'),
  (298, 'Electronics', 'Tiny Battery Pack', '🔌'),
  (299, 'Electronics', 'Tiny Microphone', '🔌'),
  (300, 'Electronics', 'Tiny Projector', '🔌');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (301, 'Animals', 'Dog', '🐾'),
  (302, 'Animals', 'Cat', '🐾'),
  (303, 'Animals', 'Rabbit', '🐾'),
  (304, 'Animals', 'Turtle', '🐾'),
  (305, 'Animals', 'Parrot', '🐾'),
  (306, 'Animals', 'Goldfish', '🐾'),
  (307, 'Animals', 'Hamster', '🐾'),
  (308, 'Animals', 'Fox', '🐾'),
  (309, 'Animals', 'Owl', '🐾'),
  (310, 'Animals', 'Deer', '🐾'),
  (311, 'Animals', 'Squirrel', '🐾'),
  (312, 'Animals', 'Penguin', '🐾'),
  (313, 'Animals', 'Elephant', '🐾'),
  (314, 'Animals', 'Giraffe', '🐾'),
  (315, 'Animals', 'Lion', '🐾'),
  (316, 'Animals', 'Zebra', '🐾'),
  (317, 'Animals', 'Koala', '🐾'),
  (318, 'Animals', 'Panda', '🐾'),
  (319, 'Animals', 'Kangaroo', '🐾'),
  (320, 'Animals', 'Dolphin', '🐾'),
  (321, 'Animals', 'Butterfly', '🐾'),
  (322, 'Animals', 'Bee', '🐾'),
  (323, 'Animals', 'Frog', '🐾'),
  (324, 'Animals', 'Hedgehog', '🐾'),
  (325, 'Animals', 'Otter', '🐾'),
  (326, 'Animals', 'Peacock', '🐾'),
  (327, 'Animals', 'Flamingo', '🐾'),
  (328, 'Animals', 'Chameleon', '🐾'),
  (329, 'Animals', 'Sloth', '🐾'),
  (330, 'Animals', 'Raccoon', '🐾'),
  (331, 'Animals', 'Tiny Dog', '🐾'),
  (332, 'Animals', 'Tiny Cat', '🐾'),
  (333, 'Animals', 'Tiny Rabbit', '🐾'),
  (334, 'Animals', 'Tiny Turtle', '🐾'),
  (335, 'Animals', 'Tiny Parrot', '🐾'),
  (336, 'Animals', 'Tiny Goldfish', '🐾'),
  (337, 'Animals', 'Tiny Hamster', '🐾'),
  (338, 'Animals', 'Tiny Fox', '🐾'),
  (339, 'Animals', 'Tiny Owl', '🐾'),
  (340, 'Animals', 'Tiny Deer', '🐾'),
  (341, 'Animals', 'Tiny Squirrel', '🐾'),
  (342, 'Animals', 'Tiny Penguin', '🐾'),
  (343, 'Animals', 'Tiny Elephant', '🐾'),
  (344, 'Animals', 'Tiny Giraffe', '🐾'),
  (345, 'Animals', 'Tiny Lion', '🐾'),
  (346, 'Animals', 'Tiny Zebra', '🐾'),
  (347, 'Animals', 'Tiny Koala', '🐾'),
  (348, 'Animals', 'Tiny Panda', '🐾'),
  (349, 'Animals', 'Tiny Kangaroo', '🐾'),
  (350, 'Animals', 'Tiny Dolphin', '🐾');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (351, 'Sports', 'Soccer Ball', '⚽'),
  (352, 'Sports', 'Basketball', '⚽'),
  (353, 'Sports', 'Tennis Racket', '⚽'),
  (354, 'Sports', 'Baseball Bat', '⚽'),
  (355, 'Sports', 'Football', '⚽'),
  (356, 'Sports', 'Golf Club', '⚽'),
  (357, 'Sports', 'Hockey Stick', '⚽'),
  (358, 'Sports', 'Skateboard', '⚽'),
  (359, 'Sports', 'Boxing Glove', '⚽'),
  (360, 'Sports', 'Whistle', '⚽'),
  (361, 'Sports', 'Trophy', '⚽'),
  (362, 'Sports', 'Medal', '⚽'),
  (363, 'Sports', 'Running Shoe', '⚽'),
  (364, 'Sports', 'Jersey', '⚽'),
  (365, 'Sports', 'Helmet', '⚽'),
  (366, 'Sports', 'Frisbee', '⚽'),
  (367, 'Sports', 'Volleyball', '⚽'),
  (368, 'Sports', 'Ping Pong Paddle', '⚽'),
  (369, 'Sports', 'Bowling Ball', '⚽'),
  (370, 'Sports', 'Dumbbell', '⚽'),
  (371, 'Sports', 'Yoga Mat', '⚽'),
  (372, 'Sports', 'Jump Rope', '⚽'),
  (373, 'Sports', 'Baseball Glove', '⚽'),
  (374, 'Sports', 'Cleats', '⚽'),
  (375, 'Sports', 'Stopwatch', '⚽'),
  (376, 'Sports', 'Scoreboard', '⚽'),
  (377, 'Sports', 'Goal Net', '⚽'),
  (378, 'Sports', 'Cricket Bat', '⚽'),
  (379, 'Sports', 'Surfboard', '⚽'),
  (380, 'Sports', 'Ski', '⚽'),
  (381, 'Sports', 'Tiny Soccer Ball', '⚽'),
  (382, 'Sports', 'Tiny Basketball', '⚽'),
  (383, 'Sports', 'Tiny Tennis Racket', '⚽'),
  (384, 'Sports', 'Tiny Baseball Bat', '⚽'),
  (385, 'Sports', 'Tiny Football', '⚽'),
  (386, 'Sports', 'Tiny Golf Club', '⚽'),
  (387, 'Sports', 'Tiny Hockey Stick', '⚽'),
  (388, 'Sports', 'Tiny Skateboard', '⚽'),
  (389, 'Sports', 'Tiny Boxing Glove', '⚽'),
  (390, 'Sports', 'Tiny Whistle', '⚽'),
  (391, 'Sports', 'Tiny Trophy', '⚽'),
  (392, 'Sports', 'Tiny Medal', '⚽'),
  (393, 'Sports', 'Tiny Running Shoe', '⚽'),
  (394, 'Sports', 'Tiny Jersey', '⚽'),
  (395, 'Sports', 'Tiny Helmet', '⚽'),
  (396, 'Sports', 'Tiny Frisbee', '⚽'),
  (397, 'Sports', 'Tiny Volleyball', '⚽'),
  (398, 'Sports', 'Tiny Ping Pong Paddle', '⚽'),
  (399, 'Sports', 'Tiny Bowling Ball', '⚽'),
  (400, 'Sports', 'Tiny Dumbbell', '⚽');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (401, 'Music', 'Guitar', '🎵'),
  (402, 'Music', 'Piano', '🎵'),
  (403, 'Music', 'Drum', '🎵'),
  (404, 'Music', 'Violin', '🎵'),
  (405, 'Music', 'Trumpet', '🎵'),
  (406, 'Music', 'Flute', '🎵'),
  (407, 'Music', 'Microphone', '🎵'),
  (408, 'Music', 'Headphones', '🎵'),
  (409, 'Music', 'Sheet Music', '🎵'),
  (410, 'Music', 'Tuning Fork', '🎵'),
  (411, 'Music', 'Metronome', '🎵'),
  (412, 'Music', 'Saxophone', '🎵'),
  (413, 'Music', 'Cello', '🎵'),
  (414, 'Music', 'Harmonica', '🎵'),
  (415, 'Music', 'Tambourine', '🎵'),
  (416, 'Music', 'Keyboard', '🎵'),
  (417, 'Music', 'Turntable', '🎵'),
  (418, 'Music', 'Speaker', '🎵'),
  (419, 'Music', 'Music Stand', '🎵'),
  (420, 'Music', 'Cymbal', '🎵'),
  (421, 'Music', 'Bass Guitar', '🎵'),
  (422, 'Music', 'Accordion', '🎵'),
  (423, 'Music', 'Xylophone', '🎵'),
  (424, 'Music', 'Guitar Pick', '🎵'),
  (425, 'Music', 'Vinyl Record', '🎵'),
  (426, 'Music', 'Amp', '🎵'),
  (427, 'Music', 'Drumstick', '🎵'),
  (428, 'Music', 'Conductor Baton', '🎵'),
  (429, 'Music', 'Banjo', '🎵'),
  (430, 'Music', 'Ukulele', '🎵'),
  (431, 'Music', 'Tiny Guitar', '🎵'),
  (432, 'Music', 'Tiny Piano', '🎵'),
  (433, 'Music', 'Tiny Drum', '🎵'),
  (434, 'Music', 'Tiny Violin', '🎵'),
  (435, 'Music', 'Tiny Trumpet', '🎵'),
  (436, 'Music', 'Tiny Flute', '🎵'),
  (437, 'Music', 'Tiny Microphone', '🎵'),
  (438, 'Music', 'Tiny Headphones', '🎵'),
  (439, 'Music', 'Tiny Sheet Music', '🎵'),
  (440, 'Music', 'Tiny Tuning Fork', '🎵'),
  (441, 'Music', 'Tiny Metronome', '🎵'),
  (442, 'Music', 'Tiny Saxophone', '🎵'),
  (443, 'Music', 'Tiny Cello', '🎵'),
  (444, 'Music', 'Tiny Harmonica', '🎵'),
  (445, 'Music', 'Tiny Tambourine', '🎵'),
  (446, 'Music', 'Tiny Keyboard', '🎵'),
  (447, 'Music', 'Tiny Turntable', '🎵'),
  (448, 'Music', 'Tiny Speaker', '🎵'),
  (449, 'Music', 'Tiny Music Stand', '🎵'),
  (450, 'Music', 'Tiny Cymbal', '🎵');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (451, 'Supermarket', 'Shopping Cart', '🛒'),
  (452, 'Supermarket', 'Grocery Bag', '🛒'),
  (453, 'Supermarket', 'Cereal Box', '🛒'),
  (454, 'Supermarket', 'Milk Carton', '🛒'),
  (455, 'Supermarket', 'Bread Loaf', '🛒'),
  (456, 'Supermarket', 'Egg Carton', '🛒'),
  (457, 'Supermarket', 'Apple', '🛒'),
  (458, 'Supermarket', 'Banana', '🛒'),
  (459, 'Supermarket', 'Cheese Wheel', '🛒'),
  (460, 'Supermarket', 'Soda Can', '🛒'),
  (461, 'Supermarket', 'Coupon', '🛒'),
  (462, 'Supermarket', 'Receipt', '🛒'),
  (463, 'Supermarket', 'Barcode Scanner', '🛒'),
  (464, 'Supermarket', 'Checkout Counter', '🛒'),
  (465, 'Supermarket', 'Shopping Basket', '🛒'),
  (466, 'Supermarket', 'Canned Soup', '🛒'),
  (467, 'Supermarket', 'Juice Bottle', '🛒'),
  (468, 'Supermarket', 'Cookie Box', '🛒'),
  (469, 'Supermarket', 'Ice Cream Tub', '🛒'),
  (470, 'Supermarket', 'Pasta Box', '🛒'),
  (471, 'Supermarket', 'Rice Bag', '🛒'),
  (472, 'Supermarket', 'Coffee Bag', '🛒'),
  (473, 'Supermarket', 'Chip Bag', '🛒'),
  (474, 'Supermarket', 'Candy Bar', '🛒'),
  (475, 'Supermarket', 'Water Bottle', '🛒'),
  (476, 'Supermarket', 'Frozen Pizza', '🛒'),
  (477, 'Supermarket', 'Yogurt Cup', '🛒'),
  (478, 'Supermarket', 'Butter Stick', '🛒'),
  (479, 'Supermarket', 'Honey Jar', '🛒'),
  (480, 'Supermarket', 'Spice Rack', '🛒'),
  (481, 'Supermarket', 'Tiny Shopping Cart', '🛒'),
  (482, 'Supermarket', 'Tiny Grocery Bag', '🛒'),
  (483, 'Supermarket', 'Tiny Cereal Box', '🛒'),
  (484, 'Supermarket', 'Tiny Milk Carton', '🛒'),
  (485, 'Supermarket', 'Tiny Bread Loaf', '🛒'),
  (486, 'Supermarket', 'Tiny Egg Carton', '🛒'),
  (487, 'Supermarket', 'Tiny Apple', '🛒'),
  (488, 'Supermarket', 'Tiny Banana', '🛒'),
  (489, 'Supermarket', 'Tiny Cheese Wheel', '🛒'),
  (490, 'Supermarket', 'Tiny Soda Can', '🛒'),
  (491, 'Supermarket', 'Tiny Coupon', '🛒'),
  (492, 'Supermarket', 'Tiny Receipt', '🛒'),
  (493, 'Supermarket', 'Tiny Barcode Scanner', '🛒'),
  (494, 'Supermarket', 'Tiny Checkout Counter', '🛒'),
  (495, 'Supermarket', 'Tiny Shopping Basket', '🛒'),
  (496, 'Supermarket', 'Tiny Canned Soup', '🛒'),
  (497, 'Supermarket', 'Tiny Juice Bottle', '🛒'),
  (498, 'Supermarket', 'Tiny Cookie Box', '🛒'),
  (499, 'Supermarket', 'Tiny Ice Cream Tub', '🛒'),
  (500, 'Supermarket', 'Tiny Pasta Box', '🛒');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (501, 'Beach', 'Beach Ball', '🏖️'),
  (502, 'Beach', 'Sunscreen', '🏖️'),
  (503, 'Beach', 'Beach Towel', '🏖️'),
  (504, 'Beach', 'Flip Flops', '🏖️'),
  (505, 'Beach', 'Sunglasses', '🏖️'),
  (506, 'Beach', 'Beach Umbrella', '🏖️'),
  (507, 'Beach', 'Surfboard', '🏖️'),
  (508, 'Beach', 'Seashell', '🏖️'),
  (509, 'Beach', 'Sandcastle', '🏖️'),
  (510, 'Beach', 'Beach Chair', '🏖️'),
  (511, 'Beach', 'Snorkel', '🏖️'),
  (512, 'Beach', 'Bucket', '🏖️'),
  (513, 'Beach', 'Kite', '🏖️'),
  (514, 'Beach', 'Cooler', '🏖️'),
  (515, 'Beach', 'Life Vest', '🏖️'),
  (516, 'Beach', 'Beach Hat', '🏖️'),
  (517, 'Beach', 'Volleyball', '🏖️'),
  (518, 'Beach', 'Starfish', '🏖️'),
  (519, 'Beach', 'Palm Tree', '🏖️'),
  (520, 'Beach', 'Boogie Board', '🏖️'),
  (521, 'Beach', 'Fishing Rod', '🏖️'),
  (522, 'Beach', 'Picnic Basket', '🏖️'),
  (523, 'Beach', 'Beach Bag', '🏖️'),
  (524, 'Beach', 'Swim Goggles', '🏖️'),
  (525, 'Beach', 'Inflatable Raft', '🏖️'),
  (526, 'Beach', 'Lighthouse', '🏖️'),
  (527, 'Beach', 'Message Bottle', '🏖️'),
  (528, 'Beach', 'Sun Hat', '🏖️'),
  (529, 'Beach', 'Wetsuit', '🏖️'),
  (530, 'Beach', 'Anchor', '🏖️'),
  (531, 'Beach', 'Tiny Beach Ball', '🏖️'),
  (532, 'Beach', 'Tiny Sunscreen', '🏖️'),
  (533, 'Beach', 'Tiny Beach Towel', '🏖️'),
  (534, 'Beach', 'Tiny Flip Flops', '🏖️'),
  (535, 'Beach', 'Tiny Sunglasses', '🏖️'),
  (536, 'Beach', 'Tiny Beach Umbrella', '🏖️'),
  (537, 'Beach', 'Tiny Surfboard', '🏖️'),
  (538, 'Beach', 'Tiny Seashell', '🏖️'),
  (539, 'Beach', 'Tiny Sandcastle', '🏖️'),
  (540, 'Beach', 'Tiny Beach Chair', '🏖️'),
  (541, 'Beach', 'Tiny Snorkel', '🏖️'),
  (542, 'Beach', 'Tiny Bucket', '🏖️'),
  (543, 'Beach', 'Tiny Kite', '🏖️'),
  (544, 'Beach', 'Tiny Cooler', '🏖️'),
  (545, 'Beach', 'Tiny Life Vest', '🏖️'),
  (546, 'Beach', 'Tiny Beach Hat', '🏖️'),
  (547, 'Beach', 'Tiny Volleyball', '🏖️'),
  (548, 'Beach', 'Tiny Starfish', '🏖️'),
  (549, 'Beach', 'Tiny Palm Tree', '🏖️'),
  (550, 'Beach', 'Tiny Boogie Board', '🏖️');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (551, 'Space', 'Rocket', '🚀'),
  (552, 'Space', 'Astronaut Helmet', '🚀'),
  (553, 'Space', 'Telescope', '🚀'),
  (554, 'Space', 'Planet Model', '🚀'),
  (555, 'Space', 'Star Chart', '🚀'),
  (556, 'Space', 'Space Suit', '🚀'),
  (557, 'Space', 'Satellite', '🚀'),
  (558, 'Space', 'Moon Rock', '🚀'),
  (559, 'Space', 'Lunar Rover', '🚀'),
  (560, 'Space', 'Comet', '🚀'),
  (561, 'Space', 'Meteor', '🚀'),
  (562, 'Space', 'Space Station', '🚀'),
  (563, 'Space', 'Alien Figure', '🚀'),
  (564, 'Space', 'Constellation Map', '🚀'),
  (565, 'Space', 'Rocket Fuel Tank', '🚀'),
  (566, 'Space', 'Space Boot', '🚀'),
  (567, 'Space', 'Solar Panel', '🚀'),
  (568, 'Space', 'Radar Dish', '🚀'),
  (569, 'Space', 'UFO Model', '🚀'),
  (570, 'Space', 'Star Map', '🚀'),
  (571, 'Space', 'Cosmic Dust Jar', '🚀'),
  (572, 'Space', 'Gravity Boots', '🚀'),
  (573, 'Space', 'Jetpack', '🚀'),
  (574, 'Space', 'Space Helmet Visor', '🚀'),
  (575, 'Space', 'Nebula Poster', '🚀'),
  (576, 'Space', 'Asteroid Chunk', '🚀'),
  (577, 'Space', 'Control Panel', '🚀'),
  (578, 'Space', 'Oxygen Tank', '🚀'),
  (579, 'Space', 'Flag of Earth', '🚀'),
  (580, 'Space', 'Space Glove', '🚀'),
  (581, 'Space', 'Tiny Rocket', '🚀'),
  (582, 'Space', 'Tiny Astronaut Helmet', '🚀'),
  (583, 'Space', 'Tiny Telescope', '🚀'),
  (584, 'Space', 'Tiny Planet Model', '🚀'),
  (585, 'Space', 'Tiny Star Chart', '🚀'),
  (586, 'Space', 'Tiny Space Suit', '🚀'),
  (587, 'Space', 'Tiny Satellite', '🚀'),
  (588, 'Space', 'Tiny Moon Rock', '🚀'),
  (589, 'Space', 'Tiny Lunar Rover', '🚀'),
  (590, 'Space', 'Tiny Comet', '🚀'),
  (591, 'Space', 'Tiny Meteor', '🚀'),
  (592, 'Space', 'Tiny Space Station', '🚀'),
  (593, 'Space', 'Tiny Alien Figure', '🚀'),
  (594, 'Space', 'Tiny Constellation Map', '🚀'),
  (595, 'Space', 'Tiny Rocket Fuel Tank', '🚀'),
  (596, 'Space', 'Tiny Space Boot', '🚀'),
  (597, 'Space', 'Tiny Solar Panel', '🚀'),
  (598, 'Space', 'Tiny Radar Dish', '🚀'),
  (599, 'Space', 'Tiny UFO Model', '🚀'),
  (600, 'Space', 'Tiny Star Map', '🚀');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (601, 'Fantasy', 'Wizard Hat', '🧙'),
  (602, 'Fantasy', 'Magic Wand', '🧙'),
  (603, 'Fantasy', 'Dragon Egg', '🧙'),
  (604, 'Fantasy', 'Sword', '🧙'),
  (605, 'Fantasy', 'Shield', '🧙'),
  (606, 'Fantasy', 'Crystal Ball', '🧙'),
  (607, 'Fantasy', 'Spellbook', '🧙'),
  (608, 'Fantasy', 'Potion Bottle', '🧙'),
  (609, 'Fantasy', 'Crown', '🧙'),
  (610, 'Fantasy', 'Enchanted Ring', '🧙'),
  (611, 'Fantasy', 'Fairy Wings', '🧙'),
  (612, 'Fantasy', 'Unicorn Horn', '🧙'),
  (613, 'Fantasy', 'Cloak', '🧙'),
  (614, 'Fantasy', 'Treasure Chest', '🧙'),
  (615, 'Fantasy', 'Golden Key', '🧙'),
  (616, 'Fantasy', 'Amulet', '🧙'),
  (617, 'Fantasy', 'Wand Case', '🧙'),
  (618, 'Fantasy', 'Elf Bow', '🧙'),
  (619, 'Fantasy', 'Goblin Mask', '🧙'),
  (620, 'Fantasy', 'Castle Model', '🧙'),
  (621, 'Fantasy', 'Magic Lamp', '🧙'),
  (622, 'Fantasy', 'Rune Stone', '🧙'),
  (623, 'Fantasy', 'Griffin Feather', '🧙'),
  (624, 'Fantasy', 'Phoenix Feather', '🧙'),
  (625, 'Fantasy', 'Scepter', '🧙'),
  (626, 'Fantasy', 'Chalice', '🧙'),
  (627, 'Fantasy', 'Dragon Scale', '🧙'),
  (628, 'Fantasy', 'Spell Scroll', '🧙'),
  (629, 'Fantasy', 'Mystic Orb', '🧙'),
  (630, 'Fantasy', 'Fairy Dust Jar', '🧙'),
  (631, 'Fantasy', 'Tiny Wizard Hat', '🧙'),
  (632, 'Fantasy', 'Tiny Magic Wand', '🧙'),
  (633, 'Fantasy', 'Tiny Dragon Egg', '🧙'),
  (634, 'Fantasy', 'Tiny Sword', '🧙'),
  (635, 'Fantasy', 'Tiny Shield', '🧙'),
  (636, 'Fantasy', 'Tiny Crystal Ball', '🧙'),
  (637, 'Fantasy', 'Tiny Spellbook', '🧙'),
  (638, 'Fantasy', 'Tiny Potion Bottle', '🧙'),
  (639, 'Fantasy', 'Tiny Crown', '🧙'),
  (640, 'Fantasy', 'Tiny Enchanted Ring', '🧙'),
  (641, 'Fantasy', 'Tiny Fairy Wings', '🧙'),
  (642, 'Fantasy', 'Tiny Unicorn Horn', '🧙'),
  (643, 'Fantasy', 'Tiny Cloak', '🧙'),
  (644, 'Fantasy', 'Tiny Treasure Chest', '🧙'),
  (645, 'Fantasy', 'Tiny Golden Key', '🧙'),
  (646, 'Fantasy', 'Tiny Amulet', '🧙'),
  (647, 'Fantasy', 'Tiny Wand Case', '🧙'),
  (648, 'Fantasy', 'Tiny Elf Bow', '🧙'),
  (649, 'Fantasy', 'Tiny Goblin Mask', '🧙'),
  (650, 'Fantasy', 'Tiny Castle Model', '🧙');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (651, 'Pirates', 'Pirate Hat', '🏴‍☠️'),
  (652, 'Pirates', 'Eye Patch', '🏴‍☠️'),
  (653, 'Pirates', 'Treasure Map', '🏴‍☠️'),
  (654, 'Pirates', 'Gold Coin', '🏴‍☠️'),
  (655, 'Pirates', 'Pirate Flag', '🏴‍☠️'),
  (656, 'Pirates', 'Cutlass', '🏴‍☠️'),
  (657, 'Pirates', 'Wooden Peg Leg', '🏴‍☠️'),
  (658, 'Pirates', 'Parrot Perch', '🏴‍☠️'),
  (659, 'Pirates', 'Spyglass', '🏴‍☠️'),
  (660, 'Pirates', 'Treasure Chest', '🏴‍☠️'),
  (661, 'Pirates', 'Compass', '🏴‍☠️'),
  (662, 'Pirates', 'Rum Bottle', '🏴‍☠️'),
  (663, 'Pirates', 'Anchor', '🏴‍☠️'),
  (664, 'Pirates', 'Ship Wheel', '🏴‍☠️'),
  (665, 'Pirates', 'Cannon Ball', '🏴‍☠️'),
  (666, 'Pirates', 'Rope Coil', '🏴‍☠️'),
  (667, 'Pirates', 'Skull Flag', '🏴‍☠️'),
  (668, 'Pirates', 'Message Bottle', '🏴‍☠️'),
  (669, 'Pirates', 'Pirate Boots', '🏴‍☠️'),
  (670, 'Pirates', 'Sea Chart', '🏴‍☠️'),
  (671, 'Pirates', 'Lantern', '🏴‍☠️'),
  (672, 'Pirates', 'Hook Hand', '🏴‍☠️'),
  (673, 'Pirates', 'Pirate Bandana', '🏴‍☠️'),
  (674, 'Pirates', 'Grappling Hook', '🏴‍☠️'),
  (675, 'Pirates', 'Ship Lantern', '🏴‍☠️'),
  (676, 'Pirates', 'Barrel', '🏴‍☠️'),
  (677, 'Pirates', 'Sea Chest', '🏴‍☠️'),
  (678, 'Pirates', 'Doubloon', '🏴‍☠️'),
  (679, 'Pirates', 'Cannon', '🏴‍☠️'),
  (680, 'Pirates', 'Jolly Roger Flag', '🏴‍☠️'),
  (681, 'Pirates', 'Tiny Pirate Hat', '🏴‍☠️'),
  (682, 'Pirates', 'Tiny Eye Patch', '🏴‍☠️'),
  (683, 'Pirates', 'Tiny Treasure Map', '🏴‍☠️'),
  (684, 'Pirates', 'Tiny Gold Coin', '🏴‍☠️'),
  (685, 'Pirates', 'Tiny Pirate Flag', '🏴‍☠️'),
  (686, 'Pirates', 'Tiny Cutlass', '🏴‍☠️'),
  (687, 'Pirates', 'Tiny Wooden Peg Leg', '🏴‍☠️'),
  (688, 'Pirates', 'Tiny Parrot Perch', '🏴‍☠️'),
  (689, 'Pirates', 'Tiny Spyglass', '🏴‍☠️'),
  (690, 'Pirates', 'Tiny Treasure Chest', '🏴‍☠️'),
  (691, 'Pirates', 'Tiny Compass', '🏴‍☠️'),
  (692, 'Pirates', 'Tiny Rum Bottle', '🏴‍☠️'),
  (693, 'Pirates', 'Tiny Anchor', '🏴‍☠️'),
  (694, 'Pirates', 'Tiny Ship Wheel', '🏴‍☠️'),
  (695, 'Pirates', 'Tiny Cannon Ball', '🏴‍☠️'),
  (696, 'Pirates', 'Tiny Rope Coil', '🏴‍☠️'),
  (697, 'Pirates', 'Tiny Skull Flag', '🏴‍☠️'),
  (698, 'Pirates', 'Tiny Message Bottle', '🏴‍☠️'),
  (699, 'Pirates', 'Tiny Pirate Boots', '🏴‍☠️'),
  (700, 'Pirates', 'Tiny Sea Chart', '🏴‍☠️');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (701, 'Hospital', 'Stethoscope', '🏥'),
  (702, 'Hospital', 'Syringe', '🏥'),
  (703, 'Hospital', 'Bandage', '🏥'),
  (704, 'Hospital', 'Thermometer', '🏥'),
  (705, 'Hospital', 'Wheelchair', '🏥'),
  (706, 'Hospital', 'First Aid Kit', '🏥'),
  (707, 'Hospital', 'Medicine Bottle', '🏥'),
  (708, 'Hospital', 'Hospital Bed', '🏥'),
  (709, 'Hospital', 'X-Ray Film', '🏥'),
  (710, 'Hospital', 'Surgical Mask', '🏥'),
  (711, 'Hospital', 'Crutches', '🏥'),
  (712, 'Hospital', 'Blood Pressure Cuff', '🏥'),
  (713, 'Hospital', 'IV Bag', '🏥'),
  (714, 'Hospital', 'Scalpel', '🏥'),
  (715, 'Hospital', 'Cast', '🏥'),
  (716, 'Hospital', 'Clipboard Chart', '🏥'),
  (717, 'Hospital', 'Pill Bottle', '🏥'),
  (718, 'Hospital', 'Gauze Roll', '🏥'),
  (719, 'Hospital', 'Nurse Cap', '🏥'),
  (720, 'Hospital', 'Heart Monitor', '🏥'),
  (721, 'Hospital', 'Cotton Swab', '🏥'),
  (722, 'Hospital', 'Reflex Hammer', '🏥'),
  (723, 'Hospital', 'Splint', '🏥'),
  (724, 'Hospital', 'Otoscope', '🏥'),
  (725, 'Hospital', 'Medical Gloves', '🏥'),
  (726, 'Hospital', 'Hospital Gown', '🏥'),
  (727, 'Hospital', 'Prescription Pad', '🏥'),
  (728, 'Hospital', 'Ice Pack', '🏥'),
  (729, 'Hospital', 'Antiseptic Bottle', '🏥'),
  (730, 'Hospital', 'Hand Sanitizer', '🏥'),
  (731, 'Hospital', 'Tiny Stethoscope', '🏥'),
  (732, 'Hospital', 'Tiny Syringe', '🏥'),
  (733, 'Hospital', 'Tiny Bandage', '🏥'),
  (734, 'Hospital', 'Tiny Thermometer', '🏥'),
  (735, 'Hospital', 'Tiny Wheelchair', '🏥'),
  (736, 'Hospital', 'Tiny First Aid Kit', '🏥'),
  (737, 'Hospital', 'Tiny Medicine Bottle', '🏥'),
  (738, 'Hospital', 'Tiny Hospital Bed', '🏥'),
  (739, 'Hospital', 'Tiny X-Ray Film', '🏥'),
  (740, 'Hospital', 'Tiny Surgical Mask', '🏥'),
  (741, 'Hospital', 'Tiny Crutches', '🏥'),
  (742, 'Hospital', 'Tiny Blood Pressure Cuff', '🏥'),
  (743, 'Hospital', 'Tiny IV Bag', '🏥'),
  (744, 'Hospital', 'Tiny Scalpel', '🏥'),
  (745, 'Hospital', 'Tiny Cast', '🏥'),
  (746, 'Hospital', 'Tiny Clipboard Chart', '🏥'),
  (747, 'Hospital', 'Tiny Pill Bottle', '🏥'),
  (748, 'Hospital', 'Tiny Gauze Roll', '🏥'),
  (749, 'Hospital', 'Tiny Nurse Cap', '🏥'),
  (750, 'Hospital', 'Tiny Heart Monitor', '🏥');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (751, 'Construction', 'Hammer', '🏗️'),
  (752, 'Construction', 'Wrench', '🏗️'),
  (753, 'Construction', 'Screwdriver', '🏗️'),
  (754, 'Construction', 'Hard Hat', '🏗️'),
  (755, 'Construction', 'Nail', '🏗️'),
  (756, 'Construction', 'Tape Measure', '🏗️'),
  (757, 'Construction', 'Toolbox', '🏗️'),
  (758, 'Construction', 'Drill', '🏗️'),
  (759, 'Construction', 'Saw', '🏗️'),
  (760, 'Construction', 'Level Tool', '🏗️'),
  (761, 'Construction', 'Safety Vest', '🏗️'),
  (762, 'Construction', 'Wheelbarrow', '🏗️'),
  (763, 'Construction', 'Brick', '🏗️'),
  (764, 'Construction', 'Ladder', '🏗️'),
  (765, 'Construction', 'Blueprint', '🏗️'),
  (766, 'Construction', 'Cement Bag', '🏗️'),
  (767, 'Construction', 'Bulldozer Model', '🏗️'),
  (768, 'Construction', 'Crane Model', '🏗️'),
  (769, 'Construction', 'Traffic Cone', '🏗️'),
  (770, 'Construction', 'Work Gloves', '🏗️'),
  (771, 'Construction', 'Plywood Sheet', '🏗️'),
  (772, 'Construction', 'Pliers', '🏗️'),
  (773, 'Construction', 'Bolt', '🏗️'),
  (774, 'Construction', 'Nut', '🏗️'),
  (775, 'Construction', 'Sledgehammer', '🏗️'),
  (776, 'Construction', 'Paint Roller', '🏗️'),
  (777, 'Construction', 'Safety Goggles', '🏗️'),
  (778, 'Construction', 'Chisel', '🏗️'),
  (779, 'Construction', 'Wheel Barrow Handle', '🏗️'),
  (780, 'Construction', 'Pickaxe', '🏗️'),
  (781, 'Construction', 'Tiny Hammer', '🏗️'),
  (782, 'Construction', 'Tiny Wrench', '🏗️'),
  (783, 'Construction', 'Tiny Screwdriver', '🏗️'),
  (784, 'Construction', 'Tiny Hard Hat', '🏗️'),
  (785, 'Construction', 'Tiny Nail', '🏗️'),
  (786, 'Construction', 'Tiny Tape Measure', '🏗️'),
  (787, 'Construction', 'Tiny Toolbox', '🏗️'),
  (788, 'Construction', 'Tiny Drill', '🏗️'),
  (789, 'Construction', 'Tiny Saw', '🏗️'),
  (790, 'Construction', 'Tiny Level Tool', '🏗️'),
  (791, 'Construction', 'Tiny Safety Vest', '🏗️'),
  (792, 'Construction', 'Tiny Wheelbarrow', '🏗️'),
  (793, 'Construction', 'Tiny Brick', '🏗️'),
  (794, 'Construction', 'Tiny Ladder', '🏗️'),
  (795, 'Construction', 'Tiny Blueprint', '🏗️'),
  (796, 'Construction', 'Tiny Cement Bag', '🏗️'),
  (797, 'Construction', 'Tiny Bulldozer Model', '🏗️'),
  (798, 'Construction', 'Tiny Crane Model', '🏗️'),
  (799, 'Construction', 'Tiny Traffic Cone', '🏗️'),
  (800, 'Construction', 'Tiny Work Gloves', '🏗️');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (801, 'Christmas', 'Christmas Tree', '🎄'),
  (802, 'Christmas', 'Ornament', '🎄'),
  (803, 'Christmas', 'Stocking', '🎄'),
  (804, 'Christmas', 'Santa Hat', '🎄'),
  (805, 'Christmas', 'Present Box', '🎄'),
  (806, 'Christmas', 'Sleigh Bell', '🎄'),
  (807, 'Christmas', 'Candy Cane', '🎄'),
  (808, 'Christmas', 'Wreath', '🎄'),
  (809, 'Christmas', 'Snow Globe', '🎄'),
  (810, 'Christmas', 'Reindeer Figure', '🎄'),
  (811, 'Christmas', 'Gingerbread Man', '🎄'),
  (812, 'Christmas', 'Star Topper', '🎄'),
  (813, 'Christmas', 'String Lights', '🎄'),
  (814, 'Christmas', 'Advent Calendar', '🎄'),
  (815, 'Christmas', 'Mistletoe', '🎄'),
  (816, 'Christmas', 'Santa Figure', '🎄'),
  (817, 'Christmas', 'Elf Hat', '🎄'),
  (818, 'Christmas', 'Christmas Card', '🎄'),
  (819, 'Christmas', 'Snowman Figure', '🎄'),
  (820, 'Christmas', 'Fireplace Stocking', '🎄'),
  (821, 'Christmas', 'Hot Cocoa Mug', '🎄'),
  (822, 'Christmas', 'Nutcracker', '🎄'),
  (823, 'Christmas', 'Tinsel Strand', '🎄'),
  (824, 'Christmas', 'Christmas Cookie', '🎄'),
  (825, 'Christmas', 'Holly Sprig', '🎄'),
  (826, 'Christmas', 'Gift Ribbon', '🎄'),
  (827, 'Christmas', 'Sleigh Model', '🎄'),
  (828, 'Christmas', 'Angel Ornament', '🎄'),
  (829, 'Christmas', 'Pinecone', '🎄'),
  (830, 'Christmas', 'Ice Skate', '🎄'),
  (831, 'Christmas', 'Tiny Christmas Tree', '🎄'),
  (832, 'Christmas', 'Tiny Ornament', '🎄'),
  (833, 'Christmas', 'Tiny Stocking', '🎄'),
  (834, 'Christmas', 'Tiny Santa Hat', '🎄'),
  (835, 'Christmas', 'Tiny Present Box', '🎄'),
  (836, 'Christmas', 'Tiny Sleigh Bell', '🎄'),
  (837, 'Christmas', 'Tiny Candy Cane', '🎄'),
  (838, 'Christmas', 'Tiny Wreath', '🎄'),
  (839, 'Christmas', 'Tiny Snow Globe', '🎄'),
  (840, 'Christmas', 'Tiny Reindeer Figure', '🎄'),
  (841, 'Christmas', 'Tiny Gingerbread Man', '🎄'),
  (842, 'Christmas', 'Tiny Star Topper', '🎄'),
  (843, 'Christmas', 'Tiny String Lights', '🎄'),
  (844, 'Christmas', 'Tiny Advent Calendar', '🎄'),
  (845, 'Christmas', 'Tiny Mistletoe', '🎄'),
  (846, 'Christmas', 'Tiny Santa Figure', '🎄'),
  (847, 'Christmas', 'Tiny Elf Hat', '🎄'),
  (848, 'Christmas', 'Tiny Christmas Card', '🎄'),
  (849, 'Christmas', 'Tiny Snowman Figure', '🎄'),
  (850, 'Christmas', 'Tiny Fireplace Stocking', '🎄');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (851, 'Halloween', 'Pumpkin', '🎃'),
  (852, 'Halloween', 'Witch Hat', '🎃'),
  (853, 'Halloween', 'Ghost Costume', '🎃'),
  (854, 'Halloween', 'Candy Bucket', '🎃'),
  (855, 'Halloween', 'Spider Web', '🎃'),
  (856, 'Halloween', 'Skeleton Figure', '🎃'),
  (857, 'Halloween', 'Vampire Cape', '🎃'),
  (858, 'Halloween', 'Black Cat Figure', '🎃'),
  (859, 'Halloween', 'Broomstick', '🎃'),
  (860, 'Halloween', 'Cauldron', '🎃'),
  (861, 'Halloween', 'Bat Figure', '🎃'),
  (862, 'Halloween', 'Jack-o-Lantern', '🎃'),
  (863, 'Halloween', 'Mask', '🎃'),
  (864, 'Halloween', 'Zombie Hand', '🎃'),
  (865, 'Halloween', 'Tombstone', '🎃'),
  (866, 'Halloween', 'Candy Corn', '🎃'),
  (867, 'Halloween', 'Werewolf Mask', '🎃'),
  (868, 'Halloween', 'Cobweb', '🎃'),
  (869, 'Halloween', 'Trick-or-Treat Bag', '🎃'),
  (870, 'Halloween', 'Skull', '🎃'),
  (871, 'Halloween', 'Haunted House Model', '🎃'),
  (872, 'Halloween', 'Witch Broom', '🎃'),
  (873, 'Halloween', 'Vampire Fang', '🎃'),
  (874, 'Halloween', 'Mummy Wrap', '🎃'),
  (875, 'Halloween', 'Spider Ring', '🎃'),
  (876, 'Halloween', 'Ghost Sheet', '🎃'),
  (877, 'Halloween', 'Monster Mask', '🎃'),
  (878, 'Halloween', 'Fog Machine', '🎃'),
  (879, 'Halloween', 'Candle Lantern', '🎃'),
  (880, 'Halloween', 'Scarecrow Figure', '🎃'),
  (881, 'Halloween', 'Tiny Pumpkin', '🎃'),
  (882, 'Halloween', 'Tiny Witch Hat', '🎃'),
  (883, 'Halloween', 'Tiny Ghost Costume', '🎃'),
  (884, 'Halloween', 'Tiny Candy Bucket', '🎃'),
  (885, 'Halloween', 'Tiny Spider Web', '🎃'),
  (886, 'Halloween', 'Tiny Skeleton Figure', '🎃'),
  (887, 'Halloween', 'Tiny Vampire Cape', '🎃'),
  (888, 'Halloween', 'Tiny Black Cat Figure', '🎃'),
  (889, 'Halloween', 'Tiny Broomstick', '🎃'),
  (890, 'Halloween', 'Tiny Cauldron', '🎃'),
  (891, 'Halloween', 'Tiny Bat Figure', '🎃'),
  (892, 'Halloween', 'Tiny Jack-o-Lantern', '🎃'),
  (893, 'Halloween', 'Tiny Mask', '🎃'),
  (894, 'Halloween', 'Tiny Zombie Hand', '🎃'),
  (895, 'Halloween', 'Tiny Tombstone', '🎃'),
  (896, 'Halloween', 'Tiny Candy Corn', '🎃'),
  (897, 'Halloween', 'Tiny Werewolf Mask', '🎃'),
  (898, 'Halloween', 'Tiny Cobweb', '🎃'),
  (899, 'Halloween', 'Tiny Trick-or-Treat Bag', '🎃'),
  (900, 'Halloween', 'Tiny Skull', '🎃');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (901, 'Nature', 'Pine Cone', '🌳'),
  (902, 'Nature', 'Oak Leaf', '🌳'),
  (903, 'Nature', 'Acorn', '🌳'),
  (904, 'Nature', 'Flower Petal', '🌳'),
  (905, 'Nature', 'River Stone', '🌳'),
  (906, 'Nature', 'Bird Nest', '🌳'),
  (907, 'Nature', 'Feather', '🌳'),
  (908, 'Nature', 'Mushroom', '🌳'),
  (909, 'Nature', 'Fern Frond', '🌳'),
  (910, 'Nature', 'Moss Patch', '🌳'),
  (911, 'Nature', 'Beehive', '🌳'),
  (912, 'Nature', 'Snail Shell', '🌳'),
  (913, 'Nature', 'Log', '🌳'),
  (914, 'Nature', 'Butterfly Wing', '🌳'),
  (915, 'Nature', 'Wildflower', '🌳'),
  (916, 'Nature', 'Cattail', '🌳'),
  (917, 'Nature', 'Driftwood', '🌳'),
  (918, 'Nature', 'Berry Cluster', '🌳'),
  (919, 'Nature', 'Tree Branch', '🌳'),
  (920, 'Nature', 'Dew Drop Leaf', '🌳'),
  (921, 'Nature', 'Spider Web', '🌳'),
  (922, 'Nature', 'Ant Hill', '🌳'),
  (923, 'Nature', 'Waterfall Rock', '🌳'),
  (924, 'Nature', 'Cactus', '🌳'),
  (925, 'Nature', 'Seed Pod', '🌳'),
  (926, 'Nature', 'Twig Bundle', '🌳'),
  (927, 'Nature', 'Bark Piece', '🌳'),
  (928, 'Nature', 'Clover Leaf', '🌳'),
  (929, 'Nature', 'Vine', '🌳'),
  (930, 'Nature', 'Reed Stalk', '🌳'),
  (931, 'Nature', 'Tiny Pine Cone', '🌳'),
  (932, 'Nature', 'Tiny Oak Leaf', '🌳'),
  (933, 'Nature', 'Tiny Acorn', '🌳'),
  (934, 'Nature', 'Tiny Flower Petal', '🌳'),
  (935, 'Nature', 'Tiny River Stone', '🌳'),
  (936, 'Nature', 'Tiny Bird Nest', '🌳'),
  (937, 'Nature', 'Tiny Feather', '🌳'),
  (938, 'Nature', 'Tiny Mushroom', '🌳'),
  (939, 'Nature', 'Tiny Fern Frond', '🌳'),
  (940, 'Nature', 'Tiny Moss Patch', '🌳'),
  (941, 'Nature', 'Tiny Beehive', '🌳'),
  (942, 'Nature', 'Tiny Snail Shell', '🌳'),
  (943, 'Nature', 'Tiny Log', '🌳'),
  (944, 'Nature', 'Tiny Butterfly Wing', '🌳'),
  (945, 'Nature', 'Tiny Wildflower', '🌳'),
  (946, 'Nature', 'Tiny Cattail', '🌳'),
  (947, 'Nature', 'Tiny Driftwood', '🌳'),
  (948, 'Nature', 'Tiny Berry Cluster', '🌳'),
  (949, 'Nature', 'Tiny Tree Branch', '🌳'),
  (950, 'Nature', 'Tiny Dew Drop Leaf', '🌳');

INSERT INTO object_catalog (id, category, name, emoji) VALUES
  (951, 'Transportation', 'Car', '🚗'),
  (952, 'Transportation', 'Bicycle', '🚗'),
  (953, 'Transportation', 'Bus', '🚗'),
  (954, 'Transportation', 'Train', '🚗'),
  (955, 'Transportation', 'Airplane', '🚗'),
  (956, 'Transportation', 'Boat', '🚗'),
  (957, 'Transportation', 'Motorcycle', '🚗'),
  (958, 'Transportation', 'Scooter', '🚗'),
  (959, 'Transportation', 'Truck', '🚗'),
  (960, 'Transportation', 'Helicopter', '🚗'),
  (961, 'Transportation', 'Skateboard', '🚗'),
  (962, 'Transportation', 'Taxi', '🚗'),
  (963, 'Transportation', 'Subway Car', '🚗'),
  (964, 'Transportation', 'Sailboat', '🚗'),
  (965, 'Transportation', 'Hot Air Balloon', '🚗'),
  (966, 'Transportation', 'Tractor', '🚗'),
  (967, 'Transportation', 'Ambulance', '🚗'),
  (968, 'Transportation', 'Fire Truck', '🚗'),
  (969, 'Transportation', 'Ferry', '🚗'),
  (970, 'Transportation', 'Rickshaw', '🚗'),
  (971, 'Transportation', 'Gondola', '🚗'),
  (972, 'Transportation', 'Tram', '🚗'),
  (973, 'Transportation', 'Canoe', '🚗'),
  (974, 'Transportation', 'Wagon', '🚗'),
  (975, 'Transportation', 'Segway', '🚗'),
  (976, 'Transportation', 'Cable Car', '🚗'),
  (977, 'Transportation', 'Submarine', '🚗'),
  (978, 'Transportation', 'Race Car', '🚗'),
  (979, 'Transportation', 'Delivery Van', '🚗'),
  (980, 'Transportation', 'Rollerblades', '🚗'),
  (981, 'Transportation', 'Tiny Car', '🚗'),
  (982, 'Transportation', 'Tiny Bicycle', '🚗'),
  (983, 'Transportation', 'Tiny Bus', '🚗'),
  (984, 'Transportation', 'Tiny Train', '🚗'),
  (985, 'Transportation', 'Tiny Airplane', '🚗'),
  (986, 'Transportation', 'Tiny Boat', '🚗'),
  (987, 'Transportation', 'Tiny Motorcycle', '🚗'),
  (988, 'Transportation', 'Tiny Scooter', '🚗'),
  (989, 'Transportation', 'Tiny Truck', '🚗'),
  (990, 'Transportation', 'Tiny Helicopter', '🚗'),
  (991, 'Transportation', 'Tiny Skateboard', '🚗'),
  (992, 'Transportation', 'Tiny Taxi', '🚗'),
  (993, 'Transportation', 'Tiny Subway Car', '🚗'),
  (994, 'Transportation', 'Tiny Sailboat', '🚗'),
  (995, 'Transportation', 'Tiny Hot Air Balloon', '🚗'),
  (996, 'Transportation', 'Tiny Tractor', '🚗'),
  (997, 'Transportation', 'Tiny Ambulance', '🚗'),
  (998, 'Transportation', 'Tiny Fire Truck', '🚗'),
  (999, 'Transportation', 'Tiny Ferry', '🚗'),
  (1000, 'Transportation', 'Tiny Rickshaw', '🚗');
